---

- hosts: piserver
  tasks:
  - name: Ensure cache up to date
    become: true
    apt: update_cache=yes
  - name: Ensure dnsmasq installed
    become: true
    apt: name=dnsmasq state=present
  - name: Copy dnsmasq config
    become: true
    copy: src=files/dnsmasq.conf dest=/etc/dnsmasq.conf owner=root group=root mode=0644
  - name: Copy marsh.dr hosts
    become: true
    copy: src=files/marsh.dr.hosts dest=/etc/marsh.dr.hosts owner=root group=root mode=0644
  - name: Restart dnsmasq and ensure enabled
    become: true
    service: name=dnsmasq enabled=yes state=restarted
  - name: Allow UDP DNS traffic
    become: true
    ufw: rule=allow port=53 proto=udp
  - name: Allow TCP DNS traffic
    become: true
    ufw: rule=allow port=53 proto=tcp
  - name: Allow TCP HTTP traffic
    become: true
    ufw: rule=allow port=80 proto=tcp
